name: Update README

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Update README
        run: python update_readme.py
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README timestamp" || exit 0
          git push
        shell: bash